apiVersion: apps/v1
kind: Deployment
metadata:
  name: poruko-queue
  namespace: poruko
  labels:
    app.kubernetes.io/name: poruko
    app.kubernetes.io/component: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poruko
      app.kubernetes.io/component: queue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poruko
        app.kubernetes.io/component: queue
    spec:
      containers:
        - name: queue
          image: ghcr.io/fkupper/poruko:latest
          imagePullPolicy: IfNotPresent
          args: ["php", "artisan", "queue:work", "--verbose", "--tries=3", "--timeout=210"]
          envFrom:
            - configMapRef:
                name: poruko-config
            - secretRef:
                name: poruko-secret
          env:
            - name: RUN_MIGRATIONS
              value: "false"
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              memory: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poruko-scheduler
  namespace: poruko
  labels:
    app.kubernetes.io/name: poruko
    app.kubernetes.io/component: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poruko
      app.kubernetes.io/component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poruko
        app.kubernetes.io/component: scheduler
    spec:
      containers:
        - name: scheduler
          image: ghcr.io/fkupper/poruko:latest
          imagePullPolicy: IfNotPresent
          args: ["php", "artisan", "schedule:work"]
          envFrom:
            - configMapRef:
                name: poruko-config
            - secretRef:
                name: poruko-secret
          env:
            - name: RUN_MIGRATIONS
              value: "false"
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              memory: 256Mi
